### PR TITLE
Defer to the wiki for installation instructions

### LINKED ISSUE #102: Unify installation instructions
The installation instructions for Animate, Goalie, and Movement differ slightly. We should avoid duplication and just have them defined in one place as a single source of truth.

### LINKED ISSUE #103: Move Docker config to the docs repo
The Docker config is used for Goalie and Movement, as well as Animate, so it would make more sense to have it live in https://github.com/mesh-adaptation/mesh-adaptation-docs.

See also #102.

Linked issue: https://github.com/mesh-adaptation/mesh-adaptation-docs/issues/9.

### PR DESCRIPTION
**Pull request by jwallwork23**
Closes #103.
Closes #102.

The installation instructions for Animate, Goalie, and Movement differ slightly. We should avoid duplication and just have them defined in one place as a single source of truth.

Edit: This PR also moves the installation scripts and Docker config to the docs repo.

@acse-ej321 would you mind reviewing the [wiki page](https://github.com/mesh-adaptation/mesh-adaptation-docs/wiki/Installation-Instructions) as part of this review? Thanks!

### CODE REVIEW

**Comment by jwallwork23** [comment]
See also https://github.com/mesh-adaptation/mesh-adaptation-docs/pull/10.

**Comment by jwallwork23** [comment]
Note that this PR also now drops the Docker CI build because that now happens in the docs repo: https://github.com/mesh-adaptation/mesh-adaptation-docs/pull/10.

@acse-ej321 Ready for review.

**Review by acse-ej321 — COMMENTED** [review]
@jwallwork23 - some comments on the wiki installation page:
-	Be explicit that Firedrake/PETSc are required by changing “The options below include the installation of a custom setup for Firedrake and PETSc from either a [shell script](https://github.com/mesh-adaptation/mesh-adaptation-docs/wiki/Installation-Instructions#installing-firedrake-via-shell-script) or a [Docker image](https://github.com/mesh-adaptation/mesh-adaptation-docs/wiki/Installation-Instructions#installing-firedrake-via-docker-image)” to something like “ The mesh adaptation modules are dependent on a custom setup for Firedrake with PETSc from either a [shell script](https://github.com/mesh-adaptation/mesh-adaptation-docs/wiki/Installation-Instructions#installing-firedrake-via-shell-script) or a [Docker image](https://github.com/mesh-adaptation/mesh-adaptation-docs/wiki/Installation-Instructions#installing-firedrake-via-docker-image)”
-	In “Installing Firedrake via shell script”:
o	For consistency you could just title the second section “Installing custom Firedrake with PETSc” and have 3 sub sections “default approach”, “custom MPI approach”, “Docker image approach” with the general instructions before the sub sections to “chose from the following installation approaches.”
o	For the “Default approach” it may help to be even more explicit in the instructions, such as “Run the provided code to download and install Firedrake via the associated shell script with bespoke PETSc options”
o	For the “Custom MPI approach”, it might be worth splitting the code block into two parts for the download via curl and the installation with slightly more detailed instructions on what to edit in the shell script.
-	In “Installing Animate, Goalie, or Movement”:
o	It might be more consistent with the “Updating” section to title the section “Installing Mesh Adaptation Modules”
o	It might help to include the script to activate the Python virtual environment or include a link here to the instructions on the Firedrake site.
o	“Suppose we want to install just one of Animate, Goalie, or Movement. Denoting the package of interest by <PACKAGE>, there are two options” could be simplified to something  like “The Mesh Adaptation packages can be installed through the following options, denoting the package of interest by <PACKAGE>” 
-	In “Updating”:
o	It might be good here as well to reference the user back to the installation/update details found on the Firedrake site.

**Comment by jwallwork23** [comment]
> * In “Installing Firedrake via shell script”:
>   o	For consistency you could just title the second section “Installing custom Firedrake with PETSc” and have 3 sub sections “default approach”, “custom MPI approach”, “Docker image approach” with the general instructions before the sub sections to “chose from the following installation approaches.”

Sorry, I'm confused which section you're referring to regarding "Installing custom Firedrake with PETSc". What's it's title currently?

**Comment by jwallwork23** [comment]
@acse-ej321 Thanks for the review. I think I addressed all points except the one above. Ready for re-review.

**Review by acse-ej321 — APPROVED** [review]
@jwallwork23 - The comment above referred to the combination of the heading 'Installing Firedrake via shell script' and what is now 'Docker image approach'. All three are different approaches for installing Firedrake, so the suggestion was to group the 2 current sections under one heading such as "Installing custom Firedrake with PETSc" to contain all 3 approaches. If you leave it in two sections distinguished by shell script vs docker, you might revert to the original title for the second section of 'Installing Firedrake via docker image". This is a minor point though.

**Pull request merged**
